services:
  frontend:
    image: tr23malyarchuk/frontend:v1
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_BASE_URL=/api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: tr23malyarchuk/mavenback:v2
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/provedcode
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_pass
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: provedcode
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
