name: Main CI

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to checkout'
        required: true
        default: 'main'

jobs:
  trigger-pipelines:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Pipeline
        uses: actions/github-script@v6
        with:
          script: |
            const { data: dispatch } = await github.request('POST /repos/{owner}/{repo}/dispatches', {
              owner: 'DevOps-ProjectLevel',
              repo: 'provedcode-frontend-tr23malyarchuk',
              event_type: 'run-workflow',
              headers: {
                accept: 'application/vnd.github.v3+json',
              },
            });
            console.log('Triggered Frontend Pipeline:', dispatch);

      - name: Trigger Backend Pipeline
        uses: actions/github-script@v6
        with:
          script: |
            const { data: dispatch } = await github.request('POST /repos/{owner}/{repo}/dispatches', {
              owner: 'DevOps-ProjectLevel',
              repo: 'provedcode-backend-tr23malyarchuk',
              event_type: 'run-workflow',
              headers: {
                accept: 'application/vnd.github.v3+json',
              },
            });
            console.log('Triggered Backend Pipeline:', dispatch);

