name: United CI

on:
  workflow_dispatch:

jobs:
  trigger-frontend-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Frontend CI
      uses: peter-evans/repository-dispatch@v2
      with:
        repository: tr23malyarchuk/provedcode-frontend-tr23malyarchuk
        token: ${{ secrets.MY_PAT }}
        event-type: trigger-ci
        client-payload: '{"action": "run"}'

  trigger-backend-ci:
    runs-on: ubuntu-latest
    needs: trigger-frontend-ci

    steps:
    - name: Trigger Backend CI
      uses: peter-evans/repository-dispatch@v2
      with:
        repository: tr23malyarchuk/provedcode-backend-tr23malyarchuk
        token: ${{ secrets.MY_PAT }}
        event-type: trigger-ci
        client-payload: '{"action": "run"}'
