name: Cross-Repo CI

on:
  push:
    branches:
      - main

jobs:
  frontend:
    uses: DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk/.github/workflows/main.yml@main

  backend:
    uses: DevOps-ProjectLevel/provedcode-backend-tr23malyarchuk/.github/workflows/main.yml@main
