name: Main CI

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to checkout'
        required: true
        default: 'main'

jobs:
  trigger-pipelines:
    runs-on: ubuntu-latest
    steps:
      - name: Install httpie
        run: sudo apt-get install -y httpie

      - name: Trigger Frontend Pipeline
        run: |
          http POST https://api.github.com/repos/DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk/dispatches \
               Authorization:"token ${{ secrets.MY_PERSONAL_TOKEN }}" \
               Accept:"application/vnd.github.v3+json" \
               event_type=run-workflow

      - name: Trigger Backend Pipeline
        run: |
          http POST https://api.github.com/repos/DevOps-ProjectLevel/provedcode-backend-tr23malyarchuk/dispatches \
               Authorization:"token ${{ secrets.MY_PERSONAL_TOKEN }}" \
               Accept:"application/vnd.github.v3+json" \
               event_type=run-workflow
