name: Unified CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger_backends:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Pipeline
        uses: peter-evans/workflow-dispatch@v1
        with:
          repository: tr23malyarchuk/provedcode-backend-tr23malyarchuk
          workflow: main.yml
          ref: main

  trigger_frontends:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Pipeline
        uses: peter-evans/workflow-dispatch@v1
        with:
          repository: tr23malyarchuk/provedcode-frontend-tr23malyarchuk
          workflow: main.yml
          ref: main
