name: United CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger_backend_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Pipeline
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/tr23malyarchuk/provedcode-backend-tr23malyarchuk/actions/workflows/backend-pipeline.yml/dispatches \
            -d '{"ref":"main"}'

  trigger_frontend_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Pipeline
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/tr23malyarchuk/provedcode-frontend-tr23malyarchuk/actions/workflows/frontend-pipeline.yml/dispatches \
            -d '{"ref":"main"}'
