name: Main CI

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install python-dotenv
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv

      - name: Load environment variables
        id: load-env
        run: |
          from dotenv import load_dotenv
          import os
          load_dotenv('.env')
          print(f"API_URL={os.getenv('API_URL')}")
        env:
          ENV_FILE: .env

      - name: Trigger another workflow
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
          API_URL: ${{ secrets.API_URL }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            $API_URL \
            -d '{"ref":"main"}'
