name: Main CI

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to checkout'
        required: true
        default: 'main'

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Backend Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/bohdan/ProvedCode1/cross-repo/provedcode-cross-repo-ci/backend/repository_dispatch \
            -d '{"event_type": "trigger-backend-workflow"}'
      - name: Trigger Frontend Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/bohdan/ProvedCode1/cross-repo/provedcode-cross-repo-ci/frontend/repository_dispatch \
            -d '{"event_type": "trigger-frontend-workflow"}'
