name: Call a reusable workflow

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      PAT:
        required: true
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: tr23malyarchuk/provedcode-cross-repo-ci/.github/workflows/main.yml@main

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk/.github/workflows/main.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.PAT }}
