name: Main Workflow

on:
  workflow_dispatch:

jobs:
  trigger_reusable_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Reusable Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk
          event-type: trigger-workflow
          token: ${{ secrets.key }}
          client-payload: '{"ref": "main", "inputs": {"example_input": "value"}}'

      - name: Trigger Backend Reusable Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: DevOps-ProjectLevel/provedcode-backend-tr23malyarchuk
          event-type: trigger-workflow
          token: ${{ secrets.key }}
          client-payload: '{"ref": "main", "inputs": {"example_input": "value"}}'
