name: Cross Repo CI

on:
  workflow_call:

jobs:
  import_first_pipeline:
    uses: DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk/.github/workflows/main.yml@main

  import_second_pipeline:
    uses: DevOps-ProjectLevel/provedcode-backend-tr23malyarchuk/.github/workflows/main.yml@main
