name: Cross-Repo CI

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Call frontend workflow
        uses: DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk/.github/workflows/main.yml@main
        with:
          my_token: ${{ secrets.MY_PERSONAL_TOKEN }}

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Call backend workflow
        uses: DevOps-ProjectLevel/provedcode-backend-tr23malyarchuk/.github/workflows/main.yml@main
        with:
          my_token: ${{ secrets.MY_PERSONAL_TOKEN }}
