name: Cross Repo CI

on:
  push:
    branches:
      - main

jobs:
  trigger_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Pipeline
        env:
          REPO: DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk
          WORKFLOW: main.yml
          REF: main
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.MY_PERSONAL_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO_F/actions/workflows/$WORKFLOW/dispatches \
          -d "{\"ref\":\"$REF\"}"

  trigger_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Pipeline
        env:
          REPO: DevOps-ProjectLevel/provedcode-backend-tr23malyarchuk  
          WORKFLOW: main.yml
          REF: main
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.MY_PERSONAL_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO_B/actions/workflows/$WORKFLOW/dispatches \
          -d "{\"ref\":\"$REF\"}"
