name: Main Workflow

on:
  workflow_dispatch:

jobs:
  trigger_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.repos.createDispatchEvent({
              owner: 'DevOps-ProjectLevel',
              repo: 'provedcode-frontend-tr23malyarchuk',
              event_type: 'trigger-workflow',
              client_payload: {
                example_input: 'value'
              }
            });
            console.log('Response:', response);
        env:
          GITHUB_TOKEN: ${{ secrets.key }}

      - name: Trigger Backend Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.repos.createDispatchEvent({
              owner: 'DevOps-ProjectLevel',
              repo: 'provedcode-backend-tr23malyarchuk',
              event_type: 'trigger-workflow',
              client_payload: {
                example_input: 'value'
              }
            });
            console.log('Response:', response);
        env:
          GITHUB_TOKEN: ${{ secrets.key }}