name: Main CI
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow in another repo
        uses: actions/github-script@v6
        with:
          script: |
            const repoOwner = 'DevOps-ProjectLevel';
            const repoName = 'provedcode-frontend-tr23malyarchuk';
            const workflowId = 'main.yml'; // Имя вашего файла рабочего процесса
            const ref = 'main'; // Ветка, на которую запускается рабочий процесс

            try {
              const response = await github.rest.actions.createWorkflowDispatch({
                owner: repoOwner,
                repo: repoName,
                workflow_id: workflowId,
                ref: ref
              });
              console.log(`Workflow triggered successfully: ${response.status}`);
            } catch (error) {
              console.error(`Failed to trigger workflow: ${error}`);
              throw error;
            }
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
