name: Cross Repo CI

on:
  push:
    branches:
      - main

jobs:
  call_child_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Call Child Workflow
        uses: ./.github/workflows/main.yml
