name: Cross-Repo CI

on:
  push:
    branches:
      - main

jobs:
  frontend:
    uses: https://github.com/DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk/blob/main/.github/workflows/main.yml

  backend:
    uses: https://github.com/DevOps-ProjectLevel/provedcode-backend-tr23malyarchuk/blob/main/.github/workflows/main.yml
