name: Main CI

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to checkout'
        required: true
        default: 'main'


jobs:

  run-provedcode-pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk'
        token: ${{ secrets.MY_PAT }}
        path: 'provedcode'

    - name: Run provedcode pipeline
      working-directory: provedcode
      run: |
        # Assuming the pipeline is defined in .github/workflows/main.yml
        gh workflow run main.yml
