name: Cross Repo CI

on:
  push:
    branches:
      - main

jobs:
  trigger_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Pipeline
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk
          event-type: run-workflow
          token: ${{ secrets.MY_PERSONAL_TOKEN }}

  trigger_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Pipeline
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: DevOps-ProjectLevel/provedcode-backend-tr23malyarchuk
          event-type: run-workflow
          token: ${{ secrets.MY_PERSONAL_TOKEN }}
