name: Run Pipeline from provedcode-frontend-tr23malyarchuk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  run-provedcode-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk'
        token: ${{ secrets.MY_PERSONAL_TOKEN }}
        path: 'provedcode'
        
    - name: Run provedcode pipeline
      working-directory: provedcode
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh workflow run main.yml
