name: Main Workflow

on:
  workflow_dispatch:

jobs:
  trigger_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.key }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk/dispatches \
          -d '{"event_type": "trigger-workflow", "client_payload": {"example_input": "value"}}'

      - name: Trigger Backend Workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.key }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/DevOps-ProjectLevel/provedcode-backend-tr23malyarchuk/dispatches \
          -d '{"event_type": "trigger-workflow", "client_payload": {"example_input": "value"}}'