name: Main CI

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to checkout'
        required: true
        default: 'main'

jobs:
  trigger-pipelines:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pipeline
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ${{ secrets.REPO_FRONTEND }}
          event-type: run-workflow
          token: ${{ secrets.MY_PERSONAL_TOKEN }}

      - name: Trigger Pipeline
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ${{ secrets.REPO_BACKEND }}
          event-type: run-workflow
          token: ${{ secrets.MY_PERSONAL_TOKEN }}
