# .github/workflows/main.yml в основном репозитории
name: Cross Repo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Trigger external workflow
        run: |
          gh api --method POST /repos/DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -f event_type=trigger \
            -f client_payload='{"custom": "data"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
