name: Main CI

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to checkout'
        required: true
        default: 'main'

jobs:
  trigger-pipelines:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Pipeline
        uses: actions/github-script@v6
        with:
          script: |
            const repoOwner = 'DevOps-ProjectLevel';
            const repoName = 'provedcode-frontend-tr23malyarchuk';
            const token = process.env.GITHUB_TOKEN;

            await github.rest.repos.createDispatchEvent({
              owner: repoOwner,
              repo: repoName,
              event_type: 'run-workflow',
            });

      - name: Trigger Backend Pipeline
        uses: actions/github-script@v6
        with:
          script: |
            const repoOwner = 'DevOps-ProjectLevel';
            const repoName = 'provedcode-backend-tr23malyarchuk';
            const token = process.env.GITHUB_TOKEN;

            await github.rest.repos.createDispatchEvent({
              owner: repoOwner,
              repo: repoName,
              event_type: 'run-workflow',
            });
