name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      config-path:
        description: 'Path to the configuration file'
        required: true
        type: string
    secrets:
      PAT:
        required: true

jobs:
  call-workflow:
    uses: tr23malyarchuk/provedcode-cross-repo-ci/.github/workflows/main.yml@main
    with:
      config-path: ${{ inputs.config-path }}
    secrets:
      PAT: ${{ secrets.PAT }}

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk/.github/workflows/main.yml@58806697462707e5b211cd73747cc7395863030b
    with:
      config-path: .github/labeler.yml
    secrets:
      PAT: ${{ secrets.PAT }}
