name: Cross Repo CI

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v2
        with:
          repository: DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk
          token: ${{ secrets.MY_PERSONAL_TOKEN }}

      - name: Run frontend pipeline
        run: |
          

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend repo
        uses: actions/checkout@v2
        with:
          repository: DevOps-ProjectLevel/provedcode-backend-tr23malyarchuk
          token: ${{ secrets.MY_PERSONAL_TOKEN }}

      - name: Run backend pipeline
        run: |
          
