name: Main CI

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      PAT:
        required: true

jobs:
  reusable_workflow_job:
    uses: DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk/.github/workflows/main.yml@main
    with:
      config-path: ${{ inputs.config-path }}
    secrets:
      PAT: ${{ secrets.PAT }}
