name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-frontend-workflow:
    uses: DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk/.github/workflows/frontend.yml@9c1e1a7f8f3827b11fb9eb34ab0a21afde30e19c
    with:
      example_input: 'random value pasted'
    secrets:
      PAT: ${{ secrets.PAT }}
