name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-frontend-workflow:
    uses: DevOps-ProjectLevel/provedcode-frontend-tr23malyarchuk/.github/workflows/frontend.yml@main
    with:
      example_input: 'random value pasted'
    secrets:
      PAT: ${{ secrets.PAT }}
